### ISSUE TITLE
Error al cargar la categoria del producto

### ISSUE THREAD

**Issue by emiarias** [lucasacci/Ecommerce#20]
Al editar un producto no aparece la categoria cargada en el select, ese dato debe aparecer seleccionado en la lista.
![image](https://user-images.githubusercontent.com/18445151/191386716-f6bab1b0-2288-4364-b206-23a8bfff834a.png)

**Comment by SantiFigueroa00** [comment]
Se creo una rama para solucionar y se mergeo en dev
